### PR TITLE
Bump Metabase version to 0.46.0

### PR DESCRIPTION
**Pull request by amureki**
0.46.0 was just released:
https://github.com/metabase/metabase/releases/tag/v0.46.0

### CODE REVIEW

**Comment by paoliniluis** [comment]
@amureki we deprecated the heroku buildpak, we're not going to support this deployment anymore

**Comment by amureki** [comment]
> @amureki we deprecated the heroku buildpak, we're not going to support this deployment anymore

@paoliniluis Oh, okay, good to know. May we get a deprecation note in README.md, so people won't get confused?
Also, don't mind me asking, what is the reasoning behind this?

Best,
Rust

**Comment by codingjoe** [comment]
…or archive the repo. Kinda sad thought, easy adoption can generate a lot of up sale potential. But I am sure you have your reasons. Should it be solely about the maintenance effort, I could provide a patch that wouldn't require manual version updates. Pinning the Metabase version thought an environment variable seems more fitting for Heroku's 12-factor approach anyways.

Cheers!
Joe

**Comment by neontuna** [comment]
> @amureki we deprecated the heroku buildpak, we're not going to support this deployment anymore

Should really give folks a heads up for something like this.  I also noticed the Heroku docs were pulled from here https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-heroku - the docs should be left with a note that Heroku is no longer supported.

**Comment by alvarezloaiciga** [comment]
Do you have instructions on how to deploy to heroku if the buildpack is no longer there?

**Comment by paoliniluis** [comment]
@codingjoe @amureki @neontuna it was announced in 45 https://www.metabase.com/releases/Metabase-0.45?from_page=blog

The reason is that Heroku has been bringing lots of headaches for our users (mostly free tenant users) since day 1:
1) lack of RAM
2) requests get canceled
3) dynos switch off and people lose their subscriptions

Having said this, it's extremely easy to fork this repo and maintain it separate from Metabase :).

Also, it should be super easy to deploy a container to Heroku and use Metabase release containers

**Comment by codingjoe** [comment]
Thanks, @paoliniluis, for taking your time to answer this. I agree, Heroku is giving everyone headaches recently… That being said, we will maintain a fork for the moment. The cloud pricing isn't an option for us, since we have an open data policy, where everyone has access. Yet not everything is a data scientist. And I can't justify paying more than an Office 365 license or double GitHub for interns that only check out our data during onboarding. If you ever offer seats with different prices, I'd be love to switch ❤️ 

### Looking for a maintained version?
https://github.com/voiio/metabase-buildpack

**Pull request closed without merging**
